export type DataGoods = {
    num: string;
    name: string;
    color: string;
    price: string;
    type: string;
    appear: string;
    img: string;
    available: boolean;
}[];

const data: DataGoods = [
    {
        num: '1',
        name: 'Гитара акустическая Fender CD-60S Black',
        color: 'чёрный',
        price: '987.01',
        type: 'гитары',
        appear: '2016',
        img: 'fender CD-60S Black',
        available: false,
    },
    {
        num: '2',
        name: 'Гитара акустическая Homage LF-401C-B',
        color: 'чёрный',
        price: '346.78',
        type: 'гитары',
        appear: '2015',
        img: 'homage-lf-401c-b',
        available: true,
    },
    {
        num: '3',
        name: 'Гитара классическая Yamaha C40',
        color: 'натуральный',
        price: '573.50',
        type: 'гитары',
        appear: '2017',
        img: 'yamaha_c40',
        available: true,
    },
    {
        num: '4',
        name: 'Гитара электроакустическая LAG T70DCE',
        color: 'натуральный',
        price: '1465.20',
        type: 'гитары',
        appear: '2018',
        img: 'lag-t70',
        available: false,
    },
    {
        num: '5',
        name: 'Бас-гитара Cort Action Bass V Plus BM',
        color: 'другое',
        price: '855.68',
        type: 'гитары',
        appear: '1999',
        img: 'сort_action-bass-V-plus-BM',
        available: true,
    },
    {
        num: '6',
        name: 'Скрипка Strunal Stradivarius 150 4/4',
        color: 'натуральный',
        price: '2214.14',
        type: 'смычковые',
        appear: '1984',
        img: 'strunal_stradivarius_150_4-4_1',
        available: true,
    },
    {
        num: '7',
        name: 'Скрипка Mirra VB-290-1/4',
        color: 'натуральный',
        price: '296.19',
        type: 'смычковые',
        appear: '2019',
        img: 'mirra-vb-290-4-4',
        available: true,
    },
    {
        num: '8',
        name: 'Электроакустическая скрипка Brahner EV-380/MWH 4/4',
        color: 'белый',
        price: '650.40',
        type: 'смычковые',
        appear: '2014',
        img: 'brahner_ev-380_mwh_4-4',
        available: true,
    },
    {
        num: '9',
        name: 'Альт Gliga I-V165 Intermediate Gems 2',
        color: 'натуральный',
        price: '2198.21',
        type: 'смычковые',
        appear: '2013',
        img: 'gliga-i-v155_hbow-hj',
        available: true,
    },
    {
        num: '10',
        name: 'Виолончель Cervini HC-150 4/4',
        color: 'натуральный',
        price: '1868.70',
        type: 'смычковые',
        appear: '2010',
        img: 'cervini-hc-150-1_99ax-un',
        available: true,
    },
    {
        num: '11',
        name: 'Фортепиано Samick JS115D/EBHP',
        color: 'чёрный',
        price: '22161.18 ',
        type: 'клавишные',
        appear: '1982',
        img: 'samick-js115d-ebhp',
        available: true,
    },
    {
        num: '12',
        name: 'Фортепиано Samick JS121MD/MAHP',
        color: 'натуральный',
        price: '27085.95 ',
        type: 'клавишные',
        appear: '1999',
        img: 'samick-js121md-mahp',
        available: false,
    },
    {
        num: '13',
        name: 'Рояль Wendl&Lung W218BK',
        color: 'чёрный',
        price: '145690.00',
        type: 'клавишные',
        appear: '1897',
        img: 'wendl-and-lung-w218bk',
        available: true,
    },
    {
        num: '14',
        name: 'Цифровое пианино Casio Privia PX-770BN',
        color: 'натуральный',
        price: '3820.00',
        type: 'клавишные',
        appear: '2016',
        img: 'casio-privia-PX-770BN',
        available: true,
    },
    {
        num: '15',
        name: 'Синтезатор Casio CT-S200RD',
        color: 'другое',
        price: '747.39',
        type: 'клавишные',
        appear: '2018',
        img: 'casio-ct-s200rd',
        available: true,
    },
    {
        num: '16',
        name: 'Ударная установка Tama Imperialstar IE52KH6W-BOW',
        color: 'чёрный',
        price: '3805.92',
        type: 'ударные',
        appear: '2020',
        img: 'tama-imperialstar-ie52kh6w-bow',
        available: true,
    },
    {
        num: '17',
        name: 'Электронный барабанный модуль Yamaha DD-75',
        color: 'чёрный',
        price: '1276.51',
        type: 'ударные',
        appear: '2018',
        img: 'yamaha-dd-75-1',
        available: true,
    },
    {
        num: '18',
        name: 'Ударная установка Sonor AQ2 Bop Set TQZ 17503740',
        color: 'белый',
        price: '4873.41',
        type: 'ударные',
        appear: '2007',
        img: 'sonor-aq2-bop-set-tqz',
        available: false,
    },
    {
        num: '19',
        name: 'Маршевый бас-барабан Brahner MBD-2612H/WH',
        color: 'белый',
        price: '934.08',
        type: 'ударные',
        appear: '2011',
        img: 'brahner-mbd-2612H-WH',
        available: true,
    },
    {
        num: '20',
        name: 'Электронная ударная установка Ldrums MK-1S-Yellow',
        color: 'другое',
        price: '2095.26',
        type: 'ударные',
        appear: '2019',
        img: 'ldrums-mk-1s-yellow-1',
        available: true,
    },
    {
        num: '21',
        name: 'Флейта-пикколо Brahner PF-700S',
        color: 'другое',
        price: '576.67',
        type: 'духовые',
        appear: '1999',
        img: 'brahner-pf-700s',
        available: true,
    },
    {
        num: '22',
        name: 'Кларнет Brahner C-120B',
        color: 'чёрный',
        price: '754.18',
        type: 'духовые',
        appear: '2017',
        img: 'brahner-c-120b',
        available: true,
    },
    {
        num: '23',
        name: 'Валторна Brahner FH-4100',
        color: 'другое',
        price: '4843.42',
        type: 'духовые',
        appear: '1924',
        img: 'brahner-fh-4100',
        available: false,
    },
    {
        num: '24',
        name: 'Саксофон Jupiter JTS700Q',
        color: 'другое',
        price: '2381.41',
        type: 'духовые',
        appear: '2013',
        img: 'jupiter-jts700q',
        available: true,
    },
    {
        num: '25',
        name: 'Мелодика Swan SW32J-4-BK',
        color: 'другое',
        price: '104.00',
        type: 'духовые',
        appear: '1996',
        img: 'swan-sw32j-4-bk',
        available: true,
    },
];

export default data;
